services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/DATABASE?time-submit
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db:
