import { type NextPage } from "next";
import Head from "next/head";
import { Container, CTAButton } from "../base_components";
import { ArrowRightIcon } from "@heroicons/react/24/solid";

import { trpc } from "../utils/trpc";
import BaseLayout from "../layout/base-layout";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.example.hello.useQuery({
    text: "from tRPC",
  });

  return (
    <>
      <Head>
        <title>Time Submit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <main>
          <Container className="mt-16 md:mt-44 ">
            <div className="grid grid-cols-1 gap-16 md:grid-cols-2">
              <div className="pb-16">
                <h1 className="text-4xl font-semibold sm:leading-none  md:text-6xl md:leading-snug ">
                  Seamless Time Submission
                </h1>
                <p className="mt-4 text-lg font-light text-gray-600 md:text-xl">
                  Everything in its place. Have peace of mind with your time
                </p>
                <CTAButton
                  isLink={true}
                  to="form"
                  icon={<ArrowRightIcon width={20} />}
                >
                  Start
                </CTAButton>
              </div>
              <div className="min-w-ful h-64 rounded bg-[url('https://images.unsplash.com/photo-1518976024611-28bf4b48222e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1285&q=80')] bg-cover  shadow-2xl md:h-[640px] md:w-[592]" />
            </div>
          </Container>
        </main>
      </BaseLayout>
    </>
  );
};

export default Home;
